services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: app_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_app
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: app_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel_app_pg
      POSTGRES_USER: laravel_user_pg
      POSTGRES_PASSWORD: laravel_password_pg
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laravel_user_pg -d laravel_app_pg"]
      timeout: 20s
      retries: 10

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:${APP_KEY:-}
      # MySQL Configuration (default)
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel_app
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_password
      # PostgreSQL Configuration (alternative)
      - PGSQL_HOST=localhost
      - PGSQL_PORT=5432
      - PGSQL_DATABASE=laravel_app_pg
      - PGSQL_USERNAME=laravel_user_pg
      - PGSQL_PASSWORD=laravel_password_pg
      # Redis Configuration
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=null
      - SENTRY_LARAVEL_DSN=https://5360cf1df3bb67560b555a34235000e9@o396822.ingest.us.sentry.io/4510105317867520
    volumes:
      - ./backend:/var/www/html
      - backend_storage:/var/www/html/storage
    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app_network

  # Nuxt Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:8000/api/v1/
      - VITE_APP_NAME="Vue App"
      - VITE_APP_VERSION=1.0.0
      - VITE_ENABLE_API_LOGGING=true
      - VITE_ENABLE_DEV_TOOLS=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.nuxt
    depends_on:
      - backend
    networks:
      - app_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: app_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    command: redis-server --appendonly yes

  # phpMyAdmin (MySQL management)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: app_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=laravel_user
      - PMA_PASSWORD=laravel_password
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network

  # pgAdmin (PostgreSQL management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: app_pgadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin_password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network

volumes:
  mysql_data:
  postgres_data:
  backend_storage:
  redis_data:
  pgadmin_data:

networks:
  app_network:
    driver: bridge